---
# tasks file for vagrantbox--ubuntu-desktop-basebox/add-shared-folders
- name: Add demouser to the vboxsf group
  user: name=demouser append=yes groups=vboxsf
  become: True
  tags: add-shared-folders
- name: Add vagrant to the vboxsf group
  user: name=vagrant append=yes groups=vboxsf
  become: True
  tags: add-shared-folders
- name: Add shared folders to the VM
  local_action: command /usr/local/bin/vboxmanage sharedfolder add "{{ vm }}" --name "vagrant_data" --hostpath "{{ ansible_env.PWD }}/../data" --transient --automount
  tags: add-shared-folders
