---
- name: Create the VM for the basebox
  hosts: localhost
  vars:
    osversion: 7
    osarch: x86_64
    osspin: DVD
    osbuild: 1511
    vm: "CentOS-{{ osversion }}-{{ osarch }}-{{ osspin }}-{{ osbuild }}"
    ostype: RedHat_64
    iso_mirror: "http://centos.s.uw.edu/centos/{{ osversion }}/isos/{{ osspin }}/"
  roles:
    - role: create-basebox-vm
  tags:
    - make-vm

- name: Configure the VM for vagrant
  hosts: centos-7-x86_64-dvd-1511
  vars:
    osversion: 7
    osarch: x86_64
    osspin: DVD
    osbuild: 1511
    vm: "CentOS-{{ osversion }}-{{ osarch }}-{{ osspin }}-{{ osbuild }}"
  remote_user: demouser
  roles:
    - role: configure-basebox-vm
  tags:
    - make-config
