---
# This playbook contains three plays.

# Create the VirtualBox VM if it does not already exist
- name: Create the VM for the basebox
  hosts: localhost
  roles:
    - role: virtualbox-centos-vm

# Ensure the VirtualBox VM is configure for use as a Vagrant basebox
- name: Configure the VM for vagrant
  hosts: CentOS-7-x86_64-DVD-1511
  remote_user: demouser
  roles:
    - role: vagrantbox-centos-basebox

# Package and install the VM as a Vagrant basebox
- name: Create the basebox image
  hosts: localhost
  roles:
    - role: vagrantbox-centos-basebox-install
