---
- name: Configure the VM for vagrant
  hosts: centos-7-x86_64-dvd-1511
  vars:
    osversion: 7
    osarch: x86_64
    osspin: DVD
    osbuild: 1511
    vm: "CentOS-{{ osversion }}-{{ osarch }}-{{ osspin }}-{{ osbuild }}"
  remote_user: demouser
  roles:
    - role: vagrantbox-centos-basebox
  tags:
    - vagrantbox-centos-basebox
