---
# tasks file for vagrantbox-install
- name: Remove any existing basebox with the same name
  command: vagrant box remove "{{ vm }}"
  register: result
  failed_when: "result.rc != 0 and 'The box you requested to be removed could not be found.' not in result.stderr"
  changed_when: result.rc == 0
- name: Install the new basebox
  command: vagrant box add --name "{{ vm }}" "../boxfiles/{{ vm }}.box"
- name: Unregister base box VM
  local_action: command vboxmanage unregistervm "{{ vm }}" --delete
- name: Close and delete base box VM's disk file
  local_action: command vboxmanage closemedium disk "{{ vm_disk }}" --delete
  register: result
  failed_when: "result.rc != 0 and 'Could not find file for the medium' not in result.stderr"
  changed_when: result.rc == 0
