---
# Fetch and install pre-built Kali VM
- name: Download Kali VM appliance file
  get_url:
    url: "https://images.offensive-security.com/virtual-images/Kali-Linux-2016.2-vbox-amd64.ova"
    dest: "{{ ansible_user_dir }}/Downloads/Kali-Linux-2016.2-vbox-amd64.ova"
    checksum: "sha1:A22978E7DB5DA82A6D013DA51BE227EE2982042D"
- name: Import the Kali VM OVA file
  command: vboxmanage import Kali-Linux-2016.2-vbox-amd64.ova chdir={{ ansible_user_dir }}/Downloads
- name: Disable USB settings on the VM as they require extension packs
  command: vboxmanage modifyvm "Kali-Linux-2016.2-vbox-amd64" --usb on --usbehci off --usbxhci off
- name: Attach NIC to correct internal network
  command: vboxmanage modifyvm "Kali-Linux-2016.2-vbox-amd64" --nic1 intnet --intnet1 "net1"
