---
# The nmcli module is broken in ansible 2.4. This is supposedly fixed in
# the 2.5 devel branch.  https://github.com/ansible/ansible/pull/34577. I will
# revisit this when it is fixed in production.
#
#- name: install needed network manager libs
#  yum:
#    name: '{{ item }}'
#    state: installed
#  with_items:
#    - NetworkManager-glib
#  become: yes
#- name: Ensure default connection has been removed
#  nmcli:
#    conn_name: 'Wired connection 1'
#    state: absent
- name: Ensure NetworkManager is started and enabled at boot
  service:
    name: NetworkManager
    state: started
    enabled: yes
  become: yes
- name: Check if libvirtd service is installed
  stat:
    path: /usr/lib/systemd/system/libvirtd.service
  register: libvirtd
  changed_when: False
- name: Ensure libvirtd is stopped and disabled at boot
  service:
    name: libvirtd
    state: stopped
    enabled: no
  become: yes
  when: libvirtd.stat.isreg is defined
- name: Get list of connections
  command: nmcli c show
  register: connection_list
  changed_when: False
- name: Ensure default connection has been removed
  command: nmcli c del "Wired connection 1"
  become: yes
  when: "'Wired connection 1' in connection_list.stdout"
- name: Ensure a manual connection for {{ iface_local }} exists
  command: nmcli c add con-name {{ iface_local }} type ethernet ifname {{ iface_local }} ip4 {{ iface_local_address }} gw4 {{ iface_local_gateway }}
  become: yes
  when: iface_local_method == "manual"
- name: Ensure an auto connection for {{ iface_local }} exists
  command: nmcli c add con-name {{ iface_local }} type ethernet ifname {{ iface_local }} ipv4.method auto
  become: yes
  when: iface_local_method == "auto"
- name: Ensure IPv6 is disabled on all interfaces
  command: nmcli c mod "{{ item }}" ipv6.method ignore
  with_items:
    - "{{ iface_vagrant }}"
    - "{{ iface_local }}"
  become: yes
- name: Ensure DNS configuration from DHCP is ignored
  command: nmcli c mod "{{ item }}" ipv4.ignore-auto-dns yes
  with_items:
    - "{{ iface_vagrant }}"
    - "{{ iface_local }}"
  become: yes
- name: Ensure we use our local ipa-server as DNS
  command: nmcli c mod "{{ iface_local }}" ipv4.dns 8.8.8.8
  become: yes
- name: Ensure we don't create default routes on {{ iface_vagrant }} 
  command: nmcli c mod {{ iface_vagrant }} ipv4.never-default yes
  become: yes
