---
# Kali specific package changes
- name: Install packages specific to Kali
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - openvas
    - mitmproxy
  become: True
  notify:
    - OpenVAS setup
# Revmove packages installed as dependencies for packages we removed
- name: Autoremove packages no longer needed
  command: apt-get -y autoremove
  become: True
- name: Copy the pcap exercise files
  copy:
    dest: "/root/Desktop/"
    src: "/Users/demouser/demo/security2/data/exercises"
    owner: root
    group: root
  become: True
- name: Link the host captures directory on the desktop
  file:
    path: /root/Desktop/host_captures
    state: link
    src: /capture
  become: True
