---
# Kali specific package changes
- name: Install packages specific to Kali
  apt: name={{ item }} state=present
  with_items:
    - openvas
    - mitmproxy
  become: True
  notify:
    - OpenVAS setup
# Revmove packages installed as dependencies for packages we removed
- name: Autoremove packages no longer needed
  command: apt-get -y autoremove
  become: True
- name: Copy the pcap exercise files
  copy:
    dest: "/root/Desktop/"
    src: "{{ ansible_user_dir }}/demo/security2/data/exercies"
    owner: root
    group: root
