---
# tasks file for install-guest-addtions
#
# Ubuntu already has packages built for Guest Additions
#
- name: Install linux-headers-generic
  apt: name=linux-headers-generic state=latest
  become: True
  when: ansible_os_family == "Debian"
- name: Install build-essential 
  apt: name=build-essential state=latest
  become: True
  when: ansible_os_family == "Debian"
- name: Install dkms
  apt: name=dkms state=latest
  become: True
  when: ansible_os_family == "Debian"
- name: Install virtualbox-guest-dkms
  apt: name=virtualbox-guest-dkms state=latest
  become: True
  when: ansible_os_family == "Debian"
#
# Centos does not and has to compile them using VirtualBox's installer script.
#
- name: Add the Extra Packages for Enterprise Linux repo
  yum: name='epel-release' state="latest"
  become: True
  when: ansible_os_family == "RedHat"
- name: Ensure packages needed to build VirtualBox GuestAdditions are installed
  yum: name='bzip2,epel-release,dkms' state="latest"
  become: True
  when: ansible_os_family == "RedHat"
- name: Test if running kernel matches version of kernel-devel
  shell: 'rpm -q --queryformat "%{VERSION}-%{RELEASE}.%{ARCH}\n" kernel-devel | grep $(uname -r)'
  always_run: yes
  register: running_kernel_match
  failed_when: False
  changed_when: False
  when: ansible_os_family == "RedHat"
- name: Reboot if newer kernel has been installed
  command: '/sbin/shutdown -r now "kernel-devel is newer than running kernel. Reboot required."'
  become: True
  async: 0
  poll: 0
  when: ansible_os_family == "RedHat" and running_kernel_match.rc != 0
  ignore_errors: true
- name: Wait for reboot to complete
  pause: prompt="Press Ctrl-c when reboot completes."
  when: ansible_os_family == "RedHat" and running_kernel_match.rc != 0
  failed_when: False
  changed_when: False
- name: Insert Guest Additions CD Image
  local_action: command vboxmanage storageattach "{{ vm }}" --storagectl IDE --port 1 --device 0 --type dvddrive --medium additions
  when: ansible_os_family == "RedHat"
- name: Mount Guest Additions virtual media
  mount: name=/mnt src=/dev/cdrom fstype=iso9660 opts=ro state=mounted
  become: True
  when: ansible_os_family == "RedHat"
- name: Run the Guest Additions installer
  #command: creates=/lib/modules/{{ ansible_kernel }}/updates/dkms/vboxsf.ko
  command: "sh /mnt/VBoxLinuxAdditions.run --nox11"
  register: vboxlinuxadditions_results
  failed_when: "'Building the VirtualBox Guest Additions kernel modules[  OK  ]' not in vboxlinuxadditions_results.stderr"
  become: True
  when: ansible_os_family == "RedHat"
