---
# tasks file for package-box
- debug: msg="Ready to build the box file.  This is your only chance to make any manual configuration changes."
- name: Press Ctrl-c to continue
  pause: prompt="Press Ctrl-c to continue."
- name: Shutdown the VM
  local_action: command vboxmanage controlvm "{{ vm }}" poweroff
- name: Remove existing box file if it exists
  local_action: file path="../boxfiles/{{ vm }}.box" state=absent
- name: Build the basebox image
  local_action: command vagrant package --base "{{ vm }}" --output "../boxfiles/{{ vm }}.box"
- name: Unregister base box VM
  local_action: command vboxmanage unregistervm "{{ vm }}" --delete
- name: Close and delete base box VM's disk file
  local_action: command vboxmanage closemedium disk "{{ vm_disk }}" --delete
  register: result
  failed_when: "result.rc != 0 and 'Could not find file for the medium' not in result.stderr"
  changed_when: result.rc == 0
