---
# tasks file for vagrantbox-ubuntu-server-basebox/use-legacy-interface-names
- name: Check GRUB_CMDLINE_LINUX in /etc/default/grub
  command: egrep 'GRUB_CMDLINE_LINUX=".*net.ifnames=0 biosdevname=0.*"' /etc/default/grub
  always_run: yes
  register: grub_cmdline_updated
  ignore_errors: True
  changed_when: False
  tags: use-legacy-interface-names
- name: Update GRUB_CMDLINE_LINUX in /etc/default/grub
  lineinfile: dest=/etc/default/grub state=present backrefs=yes regexp='^GRUB_CMDLINE_LINUX="(.*)"$' line='GRUB_CMDLINE_LINUX="\1 net.ifnames=0 biosdevname=0"'
  when: grub_cmdline_updated.rc != 0
  become: True
  tags: use-legacy-interface-names
- name: Update grub config with grub-mkconfig (Debian)
  command: grub-mkconfig -o /boot/grub/grub.cfg
  become: True
  when: ansible_os_family == "Debian" and grub_cmdline_updated.rc != 0
- name: Update grub config with grub2-mkconfig (RedHat)
  command: grub2-mkconfig -o /boot/grub2/grub.cfg
  become: True
  when: ansible_os_family == "RedHat" and grub_cmdline_updated.rc != 0
- name: Configure ethX interface names in /etc/network/interfaces
  tags: vagrant
  become: True
  replace: dest=/etc/network/interfaces regexp='enp0s3' replace='eth0'
  when: ansible_os_family == "Debian"
