---
# tasks file for apachessl
- name: Install apache2 with apt
  apt: name=apache2 state=present
  when: ansible_distribution == "Ubuntu"
  become: True
- name: Enable modssl
  command: a2enmod ssl
  when: ansible_distribution == "Ubuntu"
  become: True
- name: Enable the default ssl virtualhost
  command: a2ensite default-ssl
  when: ansible_distribution == "Ubuntu"
  become: True
- name: Restart apache
  command: service apache2 restart
  when: ansible_distribution == "Ubuntu"
  become: True
