---
# tasks file for vagrant-vm-nmcli
- name: Never use eth0 for default routes
  lineinfile:
    line: "never-default=true"
    dest: "/etc/NetworkManager/system-connections/Wired connection 1"
    state: present
    insertafter: ".ipv4."
  become: yes
