---
- name: Ensure vagrant user is hidden from gdm login screen
  copy:
    src: vagrant
    dest: /var/lib/AccountsService/users
    mode: 0644
  become: yes
- import_tasks: install_common_packages.yml
- import_tasks: add_lab_user.yml
- import_tasks: pre-dns-hosts.yml
