---
# Create Kali Linux basebox
- name: Download zip
  get_url:
    url: "https://images.offensive-security.com/virtual-images/{{ vm }}-vbox-amd64.ova"
    dest: "{{ ansible_user_dir }}/Downloads/{{ vm }}-vbox-amd64.ova"
    checksum: "sha256:1b5756ead81f0ac86bf97961c75d7904d56a1462e512a6ff0263826eee898a25"
- name: Import the Kali appliance
  command: VBoxManage import {{ ansible_user_dir }}/Downloads/{{ vm }}-vbox-amd64.ova
  args:
    creates: "{{ ansible_user_dir }}/VirtualBox VMs/{{ vm }}-vbox-amd64"
- name: Change settings we don't like
  command: VBoxManage modifyvm "{{ vmcased }}-vbox-amd64" --usbehci off
- name: The following steps have to be completed manually before continuing.
  vars:
    msg: |
         login as root (password: toor)

           systemctl enable ssh
           systemctl start ssh
           useradd -b /home -U -m -s /bin/bash vagrant
           passwd vagrant
           su vagrant -c "mkdir -m 700 /home/vagrant/.ssh"
           echo 'vagrant	ALL=(ALL:ALL) NOPASSWD:ALL' > /etc/sudoers.d/vagrant
           apt-get install -y aptitude
           echo -e 'auto eth0\niface eth0 inet dhcp' > /etc/network/interfaces.d/eth0

         Then, in the VM's settings, add a port forwarding rule from port 2201 on the localhost to
         port 22 on the guest and upload the public ssh key for the vagrant user with:

           scp -P 2201 ~/keys/vagrant.pub vagrant@localhost:/home/vagrant/.ssh/authorized_keys

  debug:
    msg: "{{ msg.split('\n') }}"
- pause:
    prompt: "Press Ctrl-C when you have completed the steps above."
- name: Delete any exiting .box file
  file:
    path: "{{ vm }}.box"
    state: absent
- name: Package the base box
  command: vagrant package --base {{ vm }}-vbox-amd64 --output {{ vm }}.box
