---
# tasks file for vagrantbox-centos-basebox-installed
# From the old Makefile...
# basebox:
#         vagrant package --base $(BASEVM)
#         mv ./package.box $(BASEBOX)
#         vagrant box add --name $(BASEVM) $(BASEBOX)
#         vagrant box list
# 
# clean:
#         rm -f ./package.box $(BASEBOX)
#         vagrant box remove $(BASEVM) || true
