---
- name: Ensure packages for the IPA server are installed
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - ipa-server
    - bind-dyndb-ldap
    - ipa-server-dns
    - vsftpd
  become: yes
