---
# setsebool -P named_write_master_zones 1
# ausearch -c 'named-pkcs11' --raw | audit2allow -M my-namedpkcs11
# semodule -i my-namedpkcs11.pp
- name: Check the ipa-server-install install status
  command: grep 'The ipa-server-install command was successful' /var/log/ipaserver-install.log
  register: ipalog
  changed_when: False
  failed_when: False
  become: yes
- name: Ensure IPA server is configured (takes several minutes if it isn't)
  command: ipa-server-install --setup-dns --allow-zone-overlap -U -p password -a password -n example.com -r EXAMPLE.COM --ip-address 192.168.4.200 --hostname labipa.example.com --reverse-zone 4.168.192.in-addr.arpa. --forwarder 8.8.8.8 -U 
  become: yes
  when: ipalog.rc != 0
- name: Ensure local DNS server is used
  command: nmcli c mod enp0s8 ipv4.dns 192.168.4.200
  become: yes
- name: Ensure vsftpd is enabled and started
  service:
    name: vsftpd
    state: started
    enabled: yes
  become: yes
- name: Ensure cacert.p12 file is available via FTP
  copy:
    src: /root/cacert.p12
    dest: /var/ftp/pub/cacert.p12
    remote_src: yes
    owner: pkiuser
    group: pkiuser
    mode: 0644
  become: yes
