---
# Create Metasploitable2 basebox
- name: Download zip
  get_url:
    url: "https://svwh.dl.sourceforge.net/project/metasploitable/Metasploitable2/metasploitable-linux-2.0.0.zip"
    dest: "{{ ansible_user_dir }}/Downloads/metasploitable-linux-2.0.0.zip"
    checksum: "sha1:84133002ef79fc191e726d41265cf5ab0dfad2f0"
- name: Unpack archive
  unarchive:
    src: "{{ ansible_user_dir }}/Downloads/metasploitable-linux-2.0.0.zip"
    dest: "{{ ansible_user_dir }}/Downloads"
    remote_src: True
    creates: "{{ ansible_user_dir }}/Downloads/Metasploitable2-Linux/Metasploitable.vmdk"
- name: Create the VirtualBox VM
  command: VBoxManage createvm --name "Metasploitable2" --register
  args:
    creates: "{{ ansible_user_dir }}/VirtualBox VMs/Metasploitable2"
- name: Copy the Metasploitable disk file (vmdk) to the VM direatory
  copy:
    src: "{{ ansible_user_dir }}/Downloads/Metasploitable2-Linux/Metasploitable.vmdk"
    dest: "{{ ansible_user_dir }}/VirtualBox VMs/Metasploitable2/Metasploitable.vmdk"
    remote_src: True
- name: Configure the VirtualBox VM
  command: VBoxManage modifyvm "Metasploitable2" --ostype Ubuntu --memory 1024 --usb on --mouse usbtablet --audiocodec ad1980 --rtcuseutc on
- name: Add the SATA controller
  command: VBoxManage storagectl "Metasploitable2" --name "SATA" --add sata --controller IntelAHCI --portcount 1 --bootable on
- name: Add the Metasploitable drive to the VM
  command: VBoxManage storageattach "Metasploitable2" --storagectl "SATA" --port 0 --device 0 --type hdd --medium "{{ ansible_user_dir }}/VirtualBox VMs/Metasploitable2/Metasploitable.vmdk"
- name: The following steps have to be completed manually before continuing.
  vars:
    msg: |
         login as msfadmin and sudo -i to root (password: msfadmin)

           useradd -d /home/vagrant -m -s /bin/bash vagrant
           passwd vagrant
           su vagrant -c "mkdir -m 700 /home/vagrant/.ssh"
           echo 'vagrant	ALL=(ALL:ALL) NOPASSWD:ALL' >> /etc/sudoers

         Then, in the VM's settings, add a port forwarding rule from port 2201 on the localhost to
         port 22 on the guest and upload the public ssh key for the vagrant user with:

           scp -P 2201 ~/keys/vagrant.pub vagrant@localhost:/home/vagrant/.ssh/authorized_keys

  debug:
    msg: "{{ msg.split('\n') }}"
- pause:
    prompt: "Press Ctrl-C when you have completed the steps above."
- name: Delete any exiting .box file
  file:
    path: Metasploitable2.box
    state: absent
- name: Package the base box
  command: vagrant package --base Metasploitable2 --output Metasploitable2.box
