---
# tasks file for create-basebox-vm
  # Make sure we have the ISO file before we do anything with the VMs
- name: Check if the ISO image has already been downloaded
  stat: path="{{ iso_dest }}"
  register: iso_file_test
- name: Download ISO file
  get_url: url={{ iso_src }} dest={{ iso_dest }}
  when: iso_file_test.stat.exists == false
  # Remove any existing VM with the same name if make_clean is True
- name: Power off duplicate VM before deleting
  command: vboxmanage controlvm "{{ vm }}" poweroff
  when: make_clean == True
  ignore_errors: True
- name: Unregister duplicate VM
  command: vboxmanage unregistervm "{{ vm }}" --delete
  when: make_clean == True
  ignore_errors: True
- name: Close and delete duplicate VM's disk file
  command: vboxmanage closemedium disk "{{ vm_disk }}" --delete
  when: make_clean == True
  ignore_errors: True
  # Create the VM
- name: Create the basebox VM
  command: vboxmanage createvm --name "{{ vm }}" --register --ostype {{ ostype }}
- name: Tweak the VM settings
  command: vboxmanage modifyvm "{{ vm }}" --memory 768 --vram 12 --pae off --boot1 dvd --boot2 disk --boot3 none --rtcuseutc on --mouse usbtablet --clipboard bidirectional --usb on --nestedpaging on
- name: Configure ssh port forwarding from the local host to the VM
  command: vboxmanage modifyvm "{{ vm }}" --natpf1 "ssh,tcp,127.0.0.1,{{ localsshport }},,22"
- name: Add and IDE controller
  command: vboxmanage storagectl "{{ vm }}" --name IDE --add ide --controller PIIX4 --portcount 2 --bootable on
- name: Add a SATA controller
  command: vboxmanage storagectl "{{ vm }}" --name SATA --add sata --controller IntelAHCI --portcount 1 --bootable on
- name: Create the disk image file for the VM
  command: vboxmanage createhd --filename "{{ vm_disk }}" --size 8192 --format VMDK
- name: Attach the harddrive image file to the SATA controller
  command: vboxmanage storageattach "{{ vm }}" --storagectl SATA --port 0 --device 0 --type hdd --medium "{{ vm_disk }}" --hotpluggable on
- name: Attach the ISO file to the IDE DVD drive
  command: vboxmanage storageattach "{{ vm }}" --storagectl IDE --port 1 --device 0 --type dvddrive --medium {{ iso_dest }}
- name: Start the VM
  command: vboxmanage startvm "{{ vm }}"
- name: Pause for OS installation
  pause: prompt="Install the OS as normal.  Press Ctrl-c, when you are ready to continue."
