---
# This playbook configures the guest OS as Vagrant creates the VMs.
- name: Common configuration
  hosts: all
  roles:
    - role: vagrant-vm-all

#- name: server1 specific configuration
#  hosts: server1
#  roles:
#    - role: vagrant-vm-server1

#- name: server2 specific configuration
#  hosts: server2
#  roles:
#    - role: vagrant-vm-server2

#- name: labipa specific configuration
#  hosts: labipa
#  roles:
#    - role: vagrant-vm-labipa
