---
# This playbook configures the guest OS as Vagrant creates the VMs.
- name: Common configuration
  hosts: ipa-client
  roles:
    - role: vagrant-vm-all
    - role: vagrant-vm-reboot

- name: Configure FreeIPA hosts
  hosts: ipa-server
  roles:
    - role: vagrant-vm-all
    - role: vagrant-freeipa
    - role: vagrant-freeipa-users
    - role: vagrant-vm-reboot
