---
# tasks file for vagrantbox-ubuntu-desktop-basebox/package-defaults
- name: Remove libreoffice
  apt: name=libreoffice-common state=absent purge=yes
  when: ansible_distribution == "Ubuntu"
  become: True
- name: Remove libreoffice styles
  apt: name=libreoffice-style-galaxy state=absent purge=yes
  when: ansible_distribution == "Ubuntu"
  become: True
- name: Remove firefox
  apt: name=firefox state=absent purge=yes
  when: ansible_distribution == "Ubuntu"
  become: True
- name: Remove firefox-locale-en
  apt: name=firefox-locale-en state=absent purge=yes
  when: ansible_distribution == "Ubuntu"
  become: True
- name: Remove unity-scope-firefoxbookmarks
  apt: name=unity-scope-firefoxbookmarks state=absent purge=yes
  when: ansible_distribution == "Ubuntu"
  become: True
- name: Install chromium-browser
  apt: name=chromium-browser state=present
  when: ansible_distribution == "Ubuntu"
  become: True
- name: Autoremove packages no longer needed
  command: apt-get -y autoremove
  when: ansible_distribution == "Ubuntu"
  become: True
