---
# tasks file for apache
# Install packages that DO NOT require a GUI
- name: Install apache2 with apt
  apt: name=apache2 state=present
  become: True
- name: Enable ssl
  command: a2enmod ssl
  become: True
- name: Enable default ssl site
  command: a2ensite default-ssl.conf
  become: True
