---
# tasks file for networking
- name: Add eth1
  template:
    dest: /etc/network/interfaces.d/eth1
    src: eth1.j2
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution == "Ubuntu"
  become: True
