---
# tasks file for vagrantbox-centos-basebox-package/install-guest-addtions
- name: Add the Extra Packages for Enterprise Linux repo
  yum: name='epel-release' state="latest"
  become: True
  tags: install-guest-addtions
- name: Ensure packages needed to build VirtualBox GuestAdditions are installed
  yum: name='bzip2,epel-release,dkms' state="latest"
  become: True
  tags: install-guest-addtions
- name: Test if running kernel matches version of kernel-devel
  shell: 'rpm -q --queryformat "%{VERSION}-%{RELEASE}.%{ARCH}\n" kernel-devel | grep $(uname -r)'
  always_run: yes
  register: running_kernel_match
  failed_when: False
  tags: install-guest-addtions
- name: Reboot if newer kernel has been installed
  command: '/sbin/shutdown -r now "kernel-devel is newer than running kernel. Reboot required."'
  become: True
  async: 0
  poll: 0
  when: running_kernel_match != 0
  tags: install-guest-addtions
- name: Wait for reboot to complete
  pause: msg="Press Ctrl-c when reboot completes."
  when: running_kernel_match != 0
  tags: install-guest-addtions
- name: Insert Guest Additions CD Image
  local_action: command vboxmanage storageattach "{{ vm }}" --storagectl IDE --port 1 --device 0 --type dvddrive --medium additions
  tags: install-guest-addtions
- name: Mount Guest Additions virtual media
  mount: name=/mnt src=/dev/cdrom fstype=iso9660 opts=ro state=mounted
  become: True
  tags: install-guest-addtions
- name: Run the Guest Additions installer
  #command: creates=/lib/modules/{{ ansible_kernel }}/updates/dkms/vboxsf.ko
  command: "sh /mnt/VBoxLinuxAdditions.run --nox11"
  register: vboxlinuxadditions_results
  failed_when: "'Building the VirtualBox Guest Additions kernel modules[  OK  ]' not in vboxlinuxadditions_results.stderr"
  become: True
  tags: install-guest-addtions
