---
- hosts: all
  tasks:
    - name: ensure ntpd is at the latest version
      sudo: True
      apt: pkg=ntp state=latest
      notify:
      - restart ntpd
  handlers:
    - name: restart ntpd
      sudo: True
      service: name=ntp.service enabled=yes state=restarted
