---
# This playbook contains three plays.

# Create the VirtualBox VM for the base box
- name: Create the VirtualBox VM for the base box
  hosts: localhost
  vars:
    - vm: "ubuntu-15.10-desktop-amd64"
    - ostype: Ubuntu_64
    - iso_mirror: "http://mirror.pnl.gov/releases/15.10/"
    - localsshport: 2269
  roles:
    - role: virtualbox-vm

# Create the Vagrant base box
- name: Create the Vagrant base box
  hosts: ubuntu-15.10-desktop-amd64
  remote_user: demouser
  vars:
    - vm: "ubuntu-15.10-desktop-amd64"
  roles:
    - role: vagrantbox

# Install the Vagrant base box
- name: Install the Vagrant base box
  hosts: localhost
  vars:
    - vm: "ubuntu-15.10-desktop-amd64"
  roles:
    - role: vagrantbox-install
