---
# This playbook configures the guest OS as Vagrant creates the VMs.
- name: Common configuration
  hosts: all
  roles:
    # - role: software-updates
    - role: networking
    - role: packages

- name: Web server configuration
  hosts: pc-172.16.200.100
  roles:
    - role: apachessl

- name: Internet configuration
  hosts: Internet
  roles:
    - role: nat-firewall
    - role: caching-nameserver
