---
# This playbook configures the guest OS as Vagrant creates the VMs.
- name: Common configuration
  hosts: all
  roles:
    - role: add-demouser-account
    - role: packages
    # - role: software-updates
    - role: networking

- name: Web server configuration
  hosts: pc-172.16.200.100
  roles:
    - role: apachessl

- name: NAT Gateway config
  hosts: NAT1 NAT2
  roles:
    - role: natgw

- name: Internet configuration
  hosts: Internet
  roles:
    - role: Internet
    - role: caching-nameserver
