---
- name: Setup the VirtualBox environment
  hosts: localhost
  roles:
    - role: setup-demo-image-customizations
    - role: setup-wireshark
    - role: setup-GNS3
  tasks:
    - fail: msg="You will have to install your own Cisco IOS binary."
      ignore_errors: True
