---
# tasks file for vagrant
- name: Test if vagrant is already installed
  stat:
    path: /usr/local/bin/vagrant
  register: vagrant_installation
  changed_when: False
- name: Check the version of the installed vagrant
  shell: /usr/local/bin/vagrant --version | grep -q {{ vagrant_version }}
  when: vagrant_installation.stat.isreg is defined
  register: vagrant_version_ok
  changed_when: False
  failed_when: False
- name: Download Vagrant dmg file
  get_url:
    url: "{{ vagrant_url }}"
    dest: "{{ downloads }}/{{ vagrant_dmg }}"
  when: vagrant_installation.stat.isreg is not defined or vagrant_version_ok.rc != 0
#- name: Download Vagrant dmg file
#  command: curl -o {{ downloads }}/{{ vagrant_dmg }} {{ vagrant_url }}
#  args:
#    creates: "{{ downloads }}/{{ vagrant_dmg }}"
#  when: vagrant_installation.stat.isreg is not defined or vagrant_version_ok.rc != 0
- name: Mount Vagrant image
  command: hdiutil attach "{{ vagrant_dmg }}"
  args:
    chdir: "{{ downloads }}"
  become: yes
  changed_when: False
  when: vagrant_installation.stat.isreg is not defined or vagrant_version_ok.rc != 0
- name: Install Vagrant pkg
  command: installer -allowUntrusted -pkg "{{ mount_path }}/Vagrant.pkg" -target /
  become: yes
  when: vagrant_installation.stat.isreg is not defined or vagrant_version_ok.rc != 0
- name: Unmount Vagrant image
  command: hdiutil detach "{{ mount_path }}"
  become: yes
  changed_when: False
  when: vagrant_installation.stat.isreg is not defined or vagrant_version_ok.rc != 0
- name: Ensure {{ ansible_user_dir }}/keys directory exists
  file: path={{ ansible_user_dir }}/keys state=directory mode=700
- name: Test if {{ ansible_user_dir }}/keys/vagrant already installed
  stat:
    path: "{{ ansible_user_dir }}/keys/vagrant"
  register: keys_installation
  changed_when: False
- name: Ensure key pair in {{ ansible_user_dir }}/keys
  command: ssh-keygen -t rsa -b 4096 -f vagrant -N "" -C "vagrant public key created by vagrantbox setup"
  args:
    chdir: "{{ ansible_user_dir }}/keys"
    creates: "{{ ansible_user_dir }}/keys/vagrant"
  #when: keys_installation.stat.isreg is not defined or keys_installation.stat.isreg != 0
  when: keys_installation.stat.isreg is not defined
