---
# tasks file for vagrant-vm-metasploitable2
- name: Configure eth1
  shell: ' echo -e "auto lo\niface lo inet loopback\nauto eth0\niface eth0 inet dhcp\nauto eth1\niface eth1 inet static\naddress 192.168.201.102\nnetmask 255.255.255.0\n" > /etc/network/interfaces'
  become: yes
