---
- name: Setup the VirtualBox environment
  hosts: localhost
  roles:
    - role: wireshark
    - role: GNS3
  tasks:
    - fail: msg="You will have to install your own Cisco IOS binary."
      ignore_errors: True
