---
- hosts: localhost
  vars:
  - hdd2: "{{ ansible_user_dir }}/Virtual Machines/server2/server2-disk002.vmdk"
  tasks:
  - name: Get server2 VM info
    command: vboxmanage showvminfo server2
    changed_when: False
    register: showvminfo
  - name: Create SATA controller if needed
    command: vboxmanage storagectl server2 --name "SATA Controller" --add sata --bootable off
    when: '"SATA Controller" not in showvminfo.stdout'
  - name: Get VM hdd info
    command: vboxmanage list hdds
    changed_when: False
    register: hdds
  - name: Create second disk if needed
    command: vboxmanage createmedium disk --filename "{{ hdd2 }}" --size 1024 --format VMDK
    when: '"server2-disk002" not in hdds.stdout'
  - name: Attach newly created disk
    command: vboxmanage storageattach server2 --storagectl "SATA Controller" --port 0 --device 0 --type hdd --medium "{{ hdd2 }}"
    when: '"server2-disk002" not in hdds.stdout'
