---
# tasks file for common
- name: Install common packages
  sudo: True
  apt: "pkg={{ item }} state=latest"
  with_items:
  - dnsutils
  - sysstat
  - git
  - strace
- name: Configure system hostname
  sudo: True
  hostname: 'name={{ inventory_hostname }}'
- name: Configure system dnsdomainname
  sudo: True
  lineinfile: dest=/etc/hosts regexp='^127\.0\.1\.1' line='{{ ansible_eth1.ipv4.address }}  {{ inventory_hostname }}.example.test {{ inventory_hostname }}' owner=root group=root mode=0644 state=present
